[build]
publish = "qdrant-landing/public"
command = "cd qdrant-landing ; hugo --gc --minify -b '/'"

[context.production.environment]
HUGO_VERSION = "0.93.3"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.deploy-preview]
command = "cd qdrant-landing ; hugo --gc --minify --buildFuture -b '/'"

[context.deploy-preview.environment]
HUGO_VERSION = "0.93.3"
