baseURL = "https://qdrant.tech/"
languageCode = "en-us"
title = "Qdrant - Vector Search Engine"
theme = "qdrant"

googleAnalytics = ""
enableRobotsTXT = true
canonifyURLs = true

keywords = "search engine, neural network, matching, filter, SaaS, approximate nearest neighbor search, image search, recommender system, vectors, knn algorithm, hnsw, vector search, embeddings, similarity"


[params]
    author = "Andrey Vasnetsov"
    description = "Qdrant - Open-Source Vector Search Engine"
    keywords = ["search engine", "neural network", "matching", "filter", "SaaS",
        "approximate nearest neighbor search", "image search", "recommender system", "vectors",
        "knn algorithm", "hnsw", "vector search", "embeddings", "similarity", "simaes networks",
        "BERT", "transformer", "word2vec", "fasttext"]

    font = "Anonymous Pro"
    highlight = true
    highlightStyle = "monokailight"
    highlightLanguages = ["python", "rust", "json", "bash"]
    yandexWebmaster = ""

    logo = "/images/qdrant_logo.svg"

    github = "https://github.com/qdrant/qdrant"
    quick_start = "https://github.com/qdrant/qdrant#usage"
    tutorial = "/404.html"

    linkedin = "#"
    telegram = "https://t.me/neural_network_engineering"

    email = "info@qdrant.tech"
    location = "Berlin"


[menu]

  [[menu.main]]
    identifier = "home"
    name = "Home"
    weight = -110
    url = "/"

  [[menu.main]]
    identifier = "use-case"
    name = "Use cases"
    weight = -100
    url = "/use-cases/"

  [[menu.main]]
    identifier = "solutions"
    name = "Solutions"
    weight = -90
    url = "/solutions/"

  [[menu.main]]
    identifier = "documentation"
    name = "Documentation"
    weight = -80
    url = "/documentation/"
  

  [[menu.main]]
    identifier = "articles"
    name = "Articles"
    weight = -70
    url = "/articles/"

